name = "pubtaxi"
main = "src/index.js"
compatibility_date = "2024-03-20"

[[d1_databases]]
binding = "DB"
database_name = "pubtaxi_db"
database_id = "830827ae-6938-480e-a254-1697651765c9"

[[routes]]
pattern = "pubtaxi.lat/api/*"
custom_domain = true

[[routes]]
pattern = "pubtaxi.lat/r/*"
custom_domain = true

[vars]
BASE_URL = "https://pubtaxi.lat"
